default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pomopomo_app_development

test:
  <<: *default
  database: pomopomo_app_test

production:
  <<: *default
  database: pomopomo_production
  username: pomopomo
  password: <%= ENV['POMOPOMO_DATABASE_PASSWORD'] %>
